### ISSUE TITLE
Add `selectedDetent` bindings

### ISSUE THREAD

**Issue by samdogg7** [wojtek717/bottom-sheet#15]
### Background

Once the general fixes and improvements in [#8](#8) are merged, the package will include the concept of a `selectedDetent`, which persists the detent position when navigating to another screen.

### Proposed Enhancement

While this is a step in the right direction, it would be even more flexible if the parent view could:
1. **Set `selectedDetent`:** Allowing the parent to define the position.
2. **Listen to changes in the detent state:** Enabling the parent to respond to detent updates, which could impact other UI states.

### Benefits

- **Enhanced Control:** The parent view can more easily adapt and manage the UI based on the current detent position.
- **Increased Flexibility:** Developers gain more precise control over the presentation, aligning the detent state with other components dynamically.

**Comment by wojtek717** [comment]
Sounds like a perfect extension of this functionality, especially the ability to select detention from code,

**Comment by samdogg7** [comment]
@wojtek717 I can take this on today!

**Comment by samdogg7** [comment]
@wojtek717 it has proven to be quite a complex change to support both `isPresented` and a `Binding<Detent>`. It is definitely possible, but will require a bit of boiler plate code. 

My lean is to remove `isPresented` entirely in favor of requiring a `Binding<Detent>` + adding `Detent.hidden` case. This aligns with the keeping the implementation lightweight, opposed to blowing up package scope to support multiple initializers. 

I believe `isPresented` as a `Bool` would be deprecated in #19 in favor of `Binding<Bool>`; so one way or another the instantiator will need to create a `@State` to pass in (similar to Apple's `sheet`).

What are your thoughts?

Again, it is definitely possible to support both but will require some complex handling in `BottomSheet`

**Comment by wojtek717** [comment]
@samdogg7 
I think that a more necessary and useful option is to support Binding<Bool> isPresented to manage the display state of the sheet. It is also needed in my personal project for which this package was created :D. If you still want to continue working on selectedDetent binding then go ahead and tell me how I can help.

**Comment by samdogg7** [comment]
Okay I'll investigate supporting both 👍🏼

**Comment by wojtek717** [comment]
@samdogg7 you should get an invitation
